### ISSUE TITLE
Broken UI in small viewports

### ISSUE THREAD

**Issue by beaufortfrancois** [webgpu/webgpureport.org#15]
Recent [CSS changes](https://github.com/webgpu/webgpureport.org/compare/25abacfc53...9af0b16cd4) broke UI on small viewports in WGSL language features, misc, and workers sections.

@greggman Can you fix it?

![webgpureport org_ (3)](https://github.com/webgpu/webgpureport.org/assets/634478/b001e539-acac-4d4b-86b2-858dcc9655eb)

**Comment by greggman** [comment]
doh! fixed: https://github.com/webgpu/webgpureport.org/commit/ff52be50da642f5760b98fb6f2ce31265da828a1

**Comment by beaufortfrancois** [comment]
Thank you @greggman
